#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LonKingKanBanPD
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LonKing_MES_JX")]
	public partial class pro_ExecKanbanInv_lansqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    #endregion
		
		public pro_ExecKanbanInv_lansqDataContext() : 
				base(System.Configuration.ConfigurationManager.ConnectionStrings["KanbanModal"].ToString(), mappingSource)

        {
			OnCreated();
		}
		
		public pro_ExecKanbanInv_lansqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pro_ExecKanbanInv_lansqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pro_ExecKanbanInv_lansqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pro_ExecKanbanInv_lansqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pro_ExecKanbanInv_lansq")]
		public int pro_ExecKanbanInv_lansq([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(64)")] string kbCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> bustype, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> lineID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProID", DbType="Int")] System.Nullable<int> proID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ItemID", DbType="Int")] System.Nullable<int> itemID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Count", DbType="Int")] System.Nullable<int> count, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string operName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), kbCode, bustype, lineID, proID, itemID, count, operName);
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
